@startuml

hide circle
hide methods

package "Google Sheets" <<Cloud>> {
  class "ProjectSheet" {
    -cropNumber
    -cropName
    -plantingDate
    -continueFromPreviousYear
    -harvestDate
    -grain
    -yield
    -strawStoverHayRemoval
    -tillageDate
    -tillageType
    -nApplicationDate
    -nApplicationType
    -nApplicationAmount
    -nApplicationMethod
    -eep
  }
}

package GCP <<Cloud>> {
  package BigQuery <<Rectangle>> {
    package "Project: nori-website-prod" <<Folder>> {
      package "Dataset: supplierProjectKey" <<Folder>> {
        class "Table: Parcel_ParcelName" {
          -Number
          -Lat
          -Long
        }
        note left of "Table: Parcel_ParcelName"
          <b>Primary user:</b>Supplier
          <b>Secondary user:</b>Verifier

          <b>About this data:</b>
          Geographic data for a
          supplier's parcel. Used
          to generate a map view.
          We will need tofigure out
          how to calculate the WKT
          from this to use COMET's
          API
        end note

        package "Comet API output data" <<Rectangle>> {
          class "Table: conservationScenarioDetails_mapUnit#" {
            -activity
            -value
            -timestamp
          }
          note right of "Table: conservationScenarioDetails_mapUnit#"
            These are details about
            a supplier's projected
            scenario for if the
            supplier changes practices
            as defined in the API input
          end note

          class "Table: baselineScenarioDetails_mapUnit#" {
            -activity
            -value
            -timestamp
          }
          note left of "Table: baselineScenarioDetails_mapUnit#"
            These are details about
            a supplier's projected
            scenario for if the
            supplier continued
            practices no different
            than historically
            specified
          end note

          class "Table: historicDetails_mapUnit#" {
            -activity
            -value
            -timestamp
          }
          note right of "Table: historicDetails_mapUnit#"
            These are details about
            a supplier's historic
            practices
          end note

          note as scenarioDetails
            <b>Primary user:</b> Unknown

            <b>Nori uses this for:</b>
            - Displaying detailed information
            about what went into calculating
            a supplier's scenario projections
            in the "Baseline Report" tab

            <b>About this data:</b>
            There are <b>1,484</b> possible "activity" values
            (see the document called "(COMET) Key/value
            glossary for API" in google drive). Each
            value contains highly detailed information
            relating to how the baseline was calculated.
          end note
        }

        package "Comet API input data" <<Rectangle>> {
          class cometInput {
            -cropNumber
            -cropName
            -plantingDate
            -continueFromPreviousYear
            -harvestDate
            -grain
            -yield
            -strawStoverHayRemoval
            -tillageDate
            -tillageType
            -nApplicationDate
            -nApplicationType
            -nApplicationAmount
            -nApplicationMethod
            -eep
          }
          note right of cometInput
            <b>Primary user:</b>Supplier
            <b>Secondary user:</b>Verifier

            <b>About this data:</b>
            This is the input data
            for the COMET API
            (excluding those listed
            in additional_comet_input_data).
            When we use google sheets for
            pilot, it may be the case that
            we don't need to store this
            data in BigQuery (unknown),
            but when we switch to our own
            sheet component we will want
            to store this here
          end note
        }
      }
    }
  }

  package DataStore <<Rectangle>> {
    class CRCData {
      - selectedCometScenarioKey
      ...
    }
    class SupplierProfile
    class SupplierProject {
      -score
      -sheetUrl
      ...
    }

    class CometScenario {
      -timestamp
      -type
      -BiomassBurningCH4Uncertainty
      -BiomassBurningCH4
      -WetlandRiceCultivationCH4Uncertainty
      -WetlandRiceCultivationCH4
      -SoilCH4Uncertainty
      -LimingCO2Uncertainty
      -SoilCarbonStockEnd
      -LimingCO2
      -UreaFertilizationCO2Uncertainty
      -SoilCH4
      -SoilCarbonStock2000
      -SoilCarbonUncertainty
      -UreaFertilizationCO2
      -SoilCarbon
      -DrainedOrganicSoilsCO2
      -SoilN2OUncertainty
      -BiomassBurningCarbonUncertainty
      -WetlandRiceCultivationN2OUncertainty
      -SoilCarbonStockBegin
      -DrainedOrganicSoilsN2O
      -SoilN2O
      -BiomassBurningCarbon
      -WetlandRiceCultivationN2O
      -DrainedOrganicSoilsCO2Uncertainty
      -BiomassBurningN2O
      -BiomassBurningN2OUncertainty
      -DrainedOrganicSoilsN2OUncertainty
    }
    note right of CometScenario
      <b>Primary user:</b> Supplier

      <b>Nori uses this for:</b>
      - generating a project + crc score
      - supplier uses this info to compare
      scenario potentials

      <b>Where this data is used:</b>
      - /app/projects?projectId=supplierProjectKey
      (in the "Baseline Report" tab)

      <b>About this data:</b>
      This data comes from the "summary" sections
      at the end of a COMET API response.

      There are 2 categories of this data (indicated by "type"):
      - Baseline: a scenario projection for the case that the
      supplier continues practices that reflect his historic practices
      - Conservation: a scenario projection for the case that the
      supplier changes practices to something else (i.e. "conversion
      to non-legume grassland"). We may need an additional field to
      represent possible sub-types.

      There are effectively 5 sections within this data:
      - Carbon measurements
      - CO2 measurements
      - CH4 measurements
      - N2O measurements
      - Soil carbon stock changes through time
    end note

    class Contact {
      -type
      -SupplierProjectKey
      -FirstName
      -LastName
      -Company
      -Phone
      -Email
      -Address
      -Address2
      -City
      -State
      -Zip
    }
  }
}


package "/app/supplier/project-page?projectId=supplierProjectKey" <<Rectangle>> {
  package Supplier_Project_view <<Rectangle>> {
    package Ownership <<Rectangle>> {
      note as ownershipNote
        This contains data which can be
        read/written to Contact
      end note
    }

    package "Land Management" <<Rectangle>> {
      note as landManagementNote
        This contains a map view
        of the parcels read from
        Parcel_ParcelName
      end note
    }

    package "Baseline Report" <<Rectangle>> {


      package "Projection Review" <<Rectangle>> {
        package "Scenario Selection" <<Rectangle>> {
          note as scenarioSelectionNote
            We will need a way to calculate
            a score as well as to store
            the selected scenario in
            CRCData
          end note
        }

        package "Details" <<Rectangle>> {
          note as detailsNote
            This is a view of the
            data in the API output
            contained in BigQuery
          end note
        }

        package "Difference" <<Rectangle>> {
          note as differenceNote
            This is calculated
            by finding the difference
            between baseline and
            conservation scenarios
          end note
        }

        package "Conservation Scenario" <<Rectangle>> {
          note as conservationScenarioNote
            This contains data from
            CometScenario where
            type = Conservation
          end note
        }

        package "Baseline Scenario" <<Rectangle>> {
          note as baselineScenarioNote
            This contains data from
            CometScenario where
            type = Baseline
          end note
        }
      }
    }
  }
}

package "/app/verifier/verifier-page?projectId=supplierProjectKey" <<Rectangle>> {
  note as verifiersPageNote
    Verifiers Project Review Page
  end note
}

package /app/supplier/setup-your-project <<Rectangle>> {
  package form <<Rectangle>> {
    package sheet <<Rectangle>> {
      class sheet_data {
        -cropNumber
        -cropName
        -plantingDate
        -continueFromPreviousYear
        -harvestDate
        -grain
        -yield
        -strawStoverHayRemoval
        -tillageDate
        -tillageType
        -nApplicationDate
        -nApplicationType
        -nApplicationAmount
        -nApplicationMethod
        -eep
      }
      note left of sheet_data
        <b>Primary user:</b> Supplier
        <b>Secondary user:</b> Verifier
        (in verifier's project page as
        a verification review artifact)

        <b>Nori uses this for:</b>
        Generating a COMET API input file.

        <b>About this data:</b>
        We currently expect text input in a sheet
        which is then:
        - transformed from the sheet component
        ( [ [ ], [ ] ... ] ) and inserted into
        BigQuery using a CSV formatted stream
        - transformed into XML format and sent to the
        COMET API
        - stored in Cloud Storage as a COMET API
        input XML file for reference
      end note
    }

    note as formNote
      This is a temporary component
      that allows us to generate a
      COMET API input file which can be
      used to create Baseline +
      Conservation Scenarios seen in
      the supplier's "Baseline Report"
      tab. It will soon be replaced (also
      temporarily) by the data in
      "Google Sheets": a temporary hook up to
      Google Sheets for the duration of
      scooter+ (which will eventually
      be permanently replaced with
      our react Sheets component once
      we have finished pilot).
    end note
  }
}


package unknown <<Rectangle>> {
  class additional_comet_input_data {
    -GEOM
    -Pre-1980
    -CRP
    -CRPType
    -CRPStartYear
    -CRPEndYear
    -Year1980-2000
    -Year1980-2000_Tillage
  }
  note left of additional_comet_input_data
    These fields are required
    to build a valid
    COMET API input file.
    These might live best
    in Land Management or
    in ProjectSheet
  end note
}

ProjectSheet .left. cometInput
sheet .. cometInput
additional_comet_input_data .. SupplierProject
SupplierProfile o-- SupplierProject : supplierProfileKey
SupplierProject o-left- CRCData : supplierProjectKey
SupplierProject o-left- CometScenario : supplierProjectKey
SupplierProject o-left- Contact : supplierProjectKey
SupplierProject .. "Dataset: supplierProjectKey"
Ownership .. Contact
"Baseline Report" .. CometScenario
ProjectSheet .. SupplierProject
"Land Management" .. "Table: Parcel_ParcelName"
"Land Management" .. ProjectSheet
"Scenario Selection" .. CRCData
"Details" .. "Comet API output data"

@enduml